import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import ClientProvider from "@/components/ClientProvider/ClientProvider";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable}`}>
        <ReduxProvider>
          <ClientProvider>
            <Header />
            <Toaster />
            {children}
          </ClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
